# Copyright (C) 2026, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

"""The configuration plane adapter: `ansible-runner` over SSH.

This is the only thing in the service that changes a machine, and it changes
them by running the upstream playbooks from the collection installed in the
image. No role is rewritten, no file is rendered twice.

The `ansible.cfg` this module writes deserves an explanation, because getting
it wrong would silently change what every run does. `galaxy.yml` in
`seapath-ansible` lists `ansible.cfg` under `build_ignore`, so the installed
collection carries none of the repository's configuration. Running a collection
playbook with Ansible's defaults would gather facts on every host, continue
past a failed one, and try to install packages. The settings below reproduce
the ones that change behaviour. The ones that only change how a terminal looks
are left out, because `ansible-runner` owns stdout.
"""

from __future__ import annotations

import logging
import os
import sys
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Protocol

logger = logging.getLogger(__name__)

# Reproduced from seapath-ansible/ansible.cfg. Each line is here because it
# changes what a run does:
#
#   gathering = explicit          facts are not gathered unless a play asks
#   any_errors_fatal = True       one host failing aborts everything
#   [tags] skip = package-install packages are not installed by default
#   force_valid_group_names       group names are not mangled
#   timeout, forks                connection behaviour the CI runs with
#
# The paths are absolute: the upstream file uses relative ones and assumes the
# repository is the working directory, which is not true of a collection.
_CONFIG_TEMPLATE = """\
# Generated by seapath-webui for run {run_id}.
#
# seapath-ansible ships its ansible.cfg under galaxy.yml build_ignore, so the
# installed collection carries none of it. These are the settings that change
# what a run does, reproduced from the upstream file.

[defaults]
forks = 20
gathering = explicit
any_errors_fatal = True
force_valid_group_names = ignore
timeout = 60
host_key_checking = True
collections_path = {collections_path}
private_key_file = {private_key_file}

[tags]
skip = package-install

[ssh_connection]
# The host key comes from the machine's own filesystem, never from an
# unverified first connection. IdentitiesOnly stops the agent, if there somehow
# is one, from offering a key nobody authorised. This must stay on one line:
# a continuation would put a newline inside the value Ansible hands to ssh.
ssh_args = {ssh_args}
"""

_SSH_OPTIONS = (
    "-o UserKnownHostsFile={known_hosts}",
    "-o IdentitiesOnly=yes",
    "-o ControlMaster=auto",
    "-o ControlPersist=60s",
)


@dataclass(frozen=True)
class RunRequest:
    run_id: str
    playbook: str
    inventory_file: Path
    private_data_dir: Path
    collections_path: Path
    private_key_file: Path
    known_hosts_file: Path
    # Keys offered in addition to this node's own, which in practice means the
    # site key an operator uploaded so that one node can drive the others.
    # ssh tries each identity in turn, and IdentitiesOnly keeps it to these.
    extra_key_files: tuple[Path, ...] = ()
    extra_vars: dict[str, Any] = field(default_factory=dict)
    check: bool = False


@dataclass
class RunOutcome:
    return_code: int | None
    command: list[str]
    cancelled: bool = False
    error: str | None = None


EventHandler = Callable[[dict], None]
OutputHandler = Callable[[str], None]
CancelCheck = Callable[[], bool]


class RunAdapter(Protocol):
    """Runs one playbook to completion. The only writer of machines."""

    def execute(
        self,
        request: RunRequest,
        on_event: EventHandler,
        on_output: OutputHandler,
        should_cancel: CancelCheck,
    ) -> RunOutcome: ...


@dataclass(frozen=True)
class Preparation:
    """Everything the run is about to be launched with.

    Split out from `execute` so the exact invocation can be asserted in a test
    without an Ansible installation, a machine, or a network.
    """

    config_file: Path
    environment: dict[str, str]
    command: list[str]


def prepare(request: RunRequest) -> Preparation:
    directory = request.private_data_dir
    (directory / "env").mkdir(parents=True, exist_ok=True)
    (directory / "project").mkdir(parents=True, exist_ok=True)

    config_file = directory / "ansible.cfg"
    config_file.write_text(
        _CONFIG_TEMPLATE.format(
            run_id=request.run_id,
            collections_path=request.collections_path,
            private_key_file=request.private_key_file,
            ssh_args=" ".join(
                [
                    *_SSH_OPTIONS,
                    *(f"-o IdentityFile={path}" for path in request.extra_key_files),
                ]
            ).format(known_hosts=request.known_hosts_file),
        )
    )

    command = ["ansible-playbook", "-i", str(request.inventory_file)]
    if request.check:
        command.append("--check")
    for name, value in sorted(request.extra_vars.items()):
        command += ["--extra-vars", f"{name}={_as_ansible_literal(value)}"]
    # No --limit, ever. Which hosts a playbook plays against is a property of
    # the playbook, copied into the catalogue. Narrowing cluster_setup_ha to
    # one member of three would be accepted by Ansible and would mean nothing.
    command.append(request.playbook)

    return Preparation(
        config_file=config_file,
        environment={
            "ANSIBLE_CONFIG": str(config_file),
            "ANSIBLE_COLLECTIONS_PATH": str(request.collections_path),
            # The private key is a fact about this control machine, not about
            # the desired state, which is why it is here and not in the
            # inventory. It is also why the exported inventory works unchanged
            # on a conventional control machine that has its own key.
            "ANSIBLE_PRIVATE_KEY_FILE": str(request.private_key_file),
            "ANSIBLE_HOST_KEY_CHECKING": "True",
            "PATH": _path_with_this_interpreter_first(),
        },
        command=command,
    )


def _path_with_this_interpreter_first() -> str:
    """PATH with the directory of the running interpreter in front.

    `ansible-runner` spawns `ansible-playbook` as a child process and finds it
    on PATH, and an inherited PATH is not something this service can vouch for.
    Where the distribution ships its own Ansible, an inherited PATH runs that
    one rather than the version `requirements.txt` pins. Where it ships none,
    as on a plain Debian, there is nothing to run at all and every run ends in
    rc 127. The interpreter executing this module is by construction the one
    the pinned `ansible-core` was installed for, so its directory goes first.
    """
    directory = str(Path(sys.executable).parent)
    inherited = os.environ.get("PATH", "")
    return f"{directory}{os.pathsep}{inherited}" if inherited else directory


def _as_ansible_literal(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


class AnsibleRunnerAdapter:
    """`ansible-runner` in this process, in a thread of its own.

    Not in a sibling container. That would let a run survive a restart of the
    service and would cost access to the podman socket, which is root on the
    host, and the interruptions that actually happen are reboots, which a
    sibling container does not survive either. Recorded as D9.
    """

    def execute(
        self,
        request: RunRequest,
        on_event: EventHandler,
        on_output: OutputHandler,
        should_cancel: CancelCheck,
    ) -> RunOutcome:
        preparation = prepare(request)
        try:
            import ansible_runner
        except ImportError as error:  # pragma: no cover - the image ships it
            return RunOutcome(
                return_code=None,
                command=preparation.command,
                error=f"ansible-runner is missing from this image: {error}",
            )

        def handle_event(event: dict) -> bool:
            on_event(event)
            return True

        runner = ansible_runner.run(
            private_data_dir=str(request.private_data_dir),
            playbook=request.playbook,
            inventory=str(request.inventory_file),
            extravars=dict(request.extra_vars),
            envvars=preparation.environment,
            settings={"suppress_ansible_output": True},
            cmdline="--check" if request.check else None,
            event_handler=handle_event,
            cancel_callback=should_cancel,
            quiet=True,
        )

        on_output(runner.stdout.read() if runner.stdout else "")
        return RunOutcome(
            return_code=runner.rc,
            command=preparation.command,
            cancelled=runner.status == "canceled",
        )
