# Copyright (C) 2026, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

"""Knowing the host key of a machine before ever connecting to it.

A first SSH connection to a machine whose key is unknown either prompts, which
hangs a run forever, or is waved through with `StrictHostKeyChecking=no`, which
is a real man in the middle window on the administration network. Neither is
acceptable on a substation.

For the local machine there is a third answer, and it is strictly better than
both: read the host's own public host keys off its filesystem. No network is
involved, so there is nothing to intercept. The quadlet mounts `/etc/ssh` read
only for exactly this.

The same shape works for a peer at M3, where the host key travels over the
mutually authenticated TLS channel rather than over the wire unverified.

Until then a node that drives its neighbours with the site key has to learn
their host keys somehow, and `ssh-keyscan` is the only source available. That
is trust on first use, so it is done in the open: the scan reports fingerprints,
an operator compares them with `ssh-keygen -lf /etc/ssh/ssh_host_*.pub` on each
machine, and only what they accept is written. The accepted keys live in their
own record, so the local ones can be rewritten at every start without losing
them.
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# Modern algorithms only. An RSA host key still works, but offering it here
# would let a downgrade decide which key gets compared.
_HOST_KEY_FILES = ("ssh_host_ed25519_key.pub", "ssh_host_ecdsa_key.pub")

_HEADER = (
    "# Generated by seapath-webui from the host's own public host keys.\n"
    "# Read from the filesystem, never from the network.\n"
)


def read_local_host_keys(ssh_config_dir: Path) -> list[str]:
    """The machine's public host keys, as `<type> <blob>` without a comment."""
    keys: list[str] = []
    for name in _HOST_KEY_FILES:
        try:
            content = (ssh_config_dir / name).read_text().strip()
        except OSError:
            continue
        fields = content.split()
        if len(fields) >= 2:
            keys.append(f"{fields[0]} {fields[1]}")
    return keys


def render(entries: dict[str, list[str]]) -> str:
    """`known_hosts` content: one line per name and per key, sorted."""
    lines = []
    for name in sorted(entries):
        for key in sorted(entries[name]):
            lines.append(f"{name} {key}")
    return _HEADER + "".join(f"{line}\n" for line in lines)


def peer_record_file(known_hosts_file: Path) -> Path:
    return known_hosts_file.with_name(known_hosts_file.name + ".peers")


def read_peers(known_hosts_file: Path) -> dict[str, list[str]]:
    """The peer host keys an operator has accepted, by address."""
    try:
        content = peer_record_file(known_hosts_file).read_text()
    except OSError:
        return {}
    entries: dict[str, list[str]] = {}
    for line in content.splitlines():
        fields = line.split()
        if len(fields) >= 3 and not line.startswith("#"):
            entries.setdefault(fields[0], []).append(f"{fields[1]} {fields[2]}")
    return entries


def accept_peers(known_hosts_file: Path, entries: dict[str, list[str]]) -> None:
    """Record host keys for machines this node will drive, and merge them in."""
    known = read_peers(known_hosts_file)
    for address, keys in entries.items():
        for key in keys:
            if key not in known.setdefault(address, []):
                known[address].append(key)
    record = peer_record_file(known_hosts_file)
    record.parent.mkdir(parents=True, exist_ok=True)
    record.write_text(render(known))
    # The live file is updated now rather than at the next start, because the
    # operator accepted these keys in order to launch a run with them.
    _merge_into_live(known_hosts_file, known)
    logger.info("Accepted host keys for %s", ", ".join(sorted(entries)))


def forget_peer(known_hosts_file: Path, address: str) -> bool:
    known = read_peers(known_hosts_file)
    if address not in known:
        return False
    del known[address]
    peer_record_file(known_hosts_file).write_text(render(known))
    _drop_from_live(known_hosts_file, address)
    logger.info("Forgot the host keys of %s", address)
    return True


def _merge_into_live(known_hosts_file: Path, peers: dict[str, list[str]]) -> None:
    """Add the peer lines to the file ssh reads, keeping the local ones.

    The local lines are rewritten from the machine's own filesystem at every
    start, so this only ever adds. Rebuilding the whole file here would need
    the list of names this node answers to, which lives at startup.
    """
    existing = ""
    try:
        existing = known_hosts_file.read_text()
    except OSError:
        pass
    lines = [line for line in existing.splitlines() if line.strip()]
    for address in sorted(peers):
        for key in sorted(peers[address]):
            entry = f"{address} {key}"
            if entry not in lines:
                lines.append(entry)
    known_hosts_file.parent.mkdir(parents=True, exist_ok=True)
    known_hosts_file.write_text("".join(f"{line}\n" for line in lines))


def _drop_from_live(known_hosts_file: Path, address: str) -> None:
    try:
        existing = known_hosts_file.read_text()
    except OSError:
        return
    kept = [
        line
        for line in existing.splitlines()
        if not line.split()[:1] == [address] or line.startswith("#")
    ]
    known_hosts_file.write_text("".join(f"{line}\n" for line in kept))


def ensure_local(
    known_hosts_file: Path,
    ssh_config_dir: Path,
    names: list[str],
) -> bool:
    """Record this machine's host keys under every name it answers to.

    Returns whether the file changed. Rewritten wholesale rather than merged:
    unlike `authorized_keys`, this file belongs to the service alone, so there
    is nothing of anyone else's in it to preserve.
    """
    keys = read_local_host_keys(ssh_config_dir)
    if not keys:
        logger.warning(
            "No SSH host key found under %s, so runs against this machine "
            "would have to accept an unverified key. Check that the quadlet "
            "mounts /etc/ssh.",
            ssh_config_dir,
        )
        return False

    entries = {name: list(keys) for name in names if name}
    # The peers an operator accepted are merged back in, because this file is
    # rewritten wholesale at every start and they must survive it.
    for address, peer_keys in read_peers(known_hosts_file).items():
        entries.setdefault(address, []).extend(peer_keys)
    content = render(entries)
    known_hosts_file.parent.mkdir(parents=True, exist_ok=True)
    if known_hosts_file.exists() and known_hosts_file.read_text() == content:
        return False
    known_hosts_file.write_text(content)
    logger.info(
        "Recorded %d host key(s) for %s in %s",
        len(keys),
        ", ".join(names),
        known_hosts_file,
    )
    return True
